# Generated by Django 5.2.8 on 2025-11-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(unique=True)),
                ('branch', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
